### ISSUE TITLE
 Problem compiling last commit!

### ISSUE THREAD

**Issue by EricksOliveira** [azerothcore/mod-learn-spells#13]
error c2447 missing function header old-style formal list

.spellId

**Comment by Helias** [comment]
??
can't confirm on last commit.

![image](https://user-images.githubusercontent.com/519778/83673210-c92de000-a5d7-11ea-9866-bde2ea8d6b9e.png)


hash: https://github.com/azerothcore/azerothcore-wotlk/commit/c208a1219b54fa52501d86446a4a30edb51d0d2d
