### ISSUE TITLE
Attempted to add to 64778f8decf8

### ISSUE THREAD

**Issue by OMGhixD-OG** [azerothcore/mod-learn-spells#16]
So i tried to add this to the core. However, it didn't like that much. I'm unable to really explain what kind of an issue it is. Simply because i lack knowledge within this. But for me it is broken so i figured reporting it would be the smartest.

> Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	88	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	77	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	84	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	95	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	102	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	109	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	116	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	117	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	121	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	128	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	132	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	136	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	143	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	150	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	157	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	164	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	168	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	169	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	176	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	183	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	184	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	188	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	195	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	196	
Error (active)	E0029	expected an expression	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	203	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	77	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	84	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	88	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	95	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	102	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	109	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	116	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	117	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	121	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	128	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	132	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	136	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	143	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	150	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	157	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	164	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	168	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	169	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	176	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	183	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	184	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	188	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	195	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	196	
Error	C7555	use of designated initializers requires at least '/std:c++latest'	scripts	C:\Users\Administrator\Desktop\azerothcore-wotlk\modules\mod-learn-spells\src\mod_learnspells.cpp	203	

These are the errors i've recieved. Honestly got no idea how this would be resolved. Would really appreciate if someone could look into it. I'll even add a 10$ bounty to get it fixed : )

**Comment by BarbzYHOOL** [comment]
you touched anything?

**Comment by omghixd** [comment]
Nothing, I just added the module and this happened.

**Comment by omghixd** [comment]
So the issue was the C++ Libraries my compiler was using. going into properties of visual studio on scripts and turning it to latest quickly fixed it actually.
