### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by NiganNi** [azerothcore/mod-learn-spells#20]
When I try to compile the file I get errors:

```
1>------ Сборка начата: проект: ZERO_CHECK, Конфигурация: Release x64 ------
...........
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(79): error C2059: синтаксическая ошибка: .
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(79): error C2143: синтаксическая ошибка: отсутствие ";" перед "}"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(80): error C2143: синтаксическая ошибка: отсутствие ";" перед "}"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(80): error C2059: синтаксическая ошибка: }
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(81): error C2143: синтаксическая ошибка: отсутствие ";" перед "}"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(81): error C2059: синтаксическая ошибка: }
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(82): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(82): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(92): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(93): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(93): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(99): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(100): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
12>NPCHandler.cpp
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(100): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(106): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(107): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(107): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(113): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(114): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(114): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(125): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(126): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(126): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(140): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(141): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(141): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(147): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(148): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(148): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(154): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(155): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(155): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(161): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(162): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
12>PetHandler.cpp
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(162): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(173): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(174): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(174): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(180): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(181): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(181): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(192): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(193): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(193): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(200): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(201): error C2143: синтаксическая ошибка: отсутствие ";" перед "{"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(201): error C2447: {: отсутствует заголовок функции (возможно, используется формальный список старого типа)
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(207): error C2059: синтаксическая ошибка: ,
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(208): error C2143: синтаксическая ошибка: отсутствие ";" перед "}"
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(208): error C2059: синтаксическая ошибка: }
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(67): error C2059: синтаксическая ошибка: инициализатор члена
13>C:\Server\AzerothCore\modules\mod-learn-spells-master\src\mod_learnspells.cpp(320): error C2059: синтаксическая ошибка: <L_GRAMMAR_end_class>
..........

15>LINK : fatal error LNK1181: не удается открыть входной файл "..\scripts\Release\scripts.lib"
15>Сборка проекта "worldserver.vcxproj" завершена с ошибкой.
16>------ Сборка начата: проект: ALL_BUILD, Конфигурация: Release x64 ------
16>Building Custom Rule C:/Server/AzerothCore/CMakeLists.txt
========== Сборка: успешно: 14, с ошибками: 2, без изменений: 0, пропущено: 0 ==========
```

BRANCH(ES):
master

OPERATING SYSTEM:
Win х64

MODULES:
mod-learn-spells

**Comment by Ramys** [comment]
Hello again @Helias 
I am having the same problem mentioned above at the time of compilation.
How do i solve this? 
Can you help me?

\ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (92): error C2059: syntax error: ','
\ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (93): error C2143: syntax error: ';' absent before '{'
\ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (93): error C2447: '{': missing function header (formal old-style list?)
\ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (99): error C2059: syntax error: ','
\ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (100): error C2143: syntax error: ';' absent before '{'
\ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (100): error C2447: '{': missing function header (formal old-style list?)
\ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (106): error C2059: syntax error: ','
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (107): error C2143: syntax error: ';' absent before '{'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (107): error C2447: '{': missing function header (formal old-style list?)
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (113): error C2059: syntax error: ','
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (114): error C2143: syntax error: ';' absent before '{'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (114): error C2447: '{': missing function header (formal old-style list?)
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (125): error C2059: syntax error: ','
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (126): error C2143: syntax error: ';' absent before '{'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (126): error C2447: '{': missing function header (formal old-style list?)
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (140): error C2059: syntax error: ','
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (141): error C2143: syntax error: ';' absent before '{'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (141): error C2447: '{': missing function header (formal old-style list?)
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (147): error C2059: syntax error: ','
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (148): error C2143: syntax error: ';' absent before '{'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (148): error C2447: '{': missing function header (formal old-style list?)
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (154): error C2059: syntax error: ','
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (155): error C2143: syntax error: ';' absent before '{'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (155): error C2447: '{': missing function header (formal old-style list?)
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (161): error C2059: syntax error: ','
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (162): error C2143: syntax error: ';' absent before '{'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (162): error C2447: '{': missing function header (formal old-style list?)
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (173): error C2059: syntax error: ','
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (174): error C2143: syntax error: ';' absent before '{'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (174): error C2447: '{': missing function header (formal old-style list?)
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (180): error C2059: syntax error: ','
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (181): error C2143: syntax error: ';' absent before '{'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (181): error C2447: '{': missing function header (formal old-style list?)
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (192): error C2059: syntax error: ','
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (193): error C2143: syntax error: ';' absent before '{'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (193): error C2447: '{': missing function header (formal old-style list?)
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (200): error C2059: syntax error: ','
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (201): error C2143: syntax error: ';' absent before '{'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (201): error C2447: '{': missing function header (formal old-style list?)
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (207): error C2059: syntax error: ','
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (208): error C2143: syntax error: ';' absent before '}'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (208): error C2059: syntax error: '}'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (67): error C2059: syntax error: 'member initializer'
 \ modules \ mod-learn-spells \ src \ mod_learnspells.cpp (320): error C2059: syntax error: '<L_GRAMMAR_end_class>'

**Comment by Helias** [comment]
Using the last version I can't reproduce it, I am using:

**clang 10.0**
**g++ 9.3.0**
**Ubuntu 20.04**

**Comment by Ramys** [comment]
I am using:

**Windows 10 x 64  Pro
Visual Studio 2017 15.9.30**
**OpenSSL 1.1.1i x 64 and x 86**
**Mysql 5.7.31 wampserver**
**AzerothCore rev. aff02b0599b2+ 2020-12-10 19:13:05 +0000 (master branch) (Win64, Release)**

**Comment by Helias** [comment]
I need to know the version of gcc/g++ and/or clang and maybe cmake.
Try to update these and may you will solve, unfortunately I have no a windows machine so I can't reproduce it

**Comment by valens14** [comment]
Windows 10 user here, getting the same issue when I try to compile.  Using same as Ramys but MySQL 8.0.22 and a more recent azerothcore.  CMake version is 3.19.2.  I will try to update the files specified in the errors and see if that fixes.

**Comment by Helias** [comment]
I have no clue unfortunately :(

**Comment by Ramys** [comment]
@valens14 ..
@Helias 
This works on windows 10.

 https://mega.nz/file/8t9hTARD#n-UWc9y_motdcunex8tDOw-xZy0JHxW_fAabWRO4FkY
