### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by zyyysxd** [azerothcore/mod-learn-spells#28]
Scanning dependencies of target scripts
[ 40%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/GenLoader.cpp.o
[ 40%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-learn-spells-master/src/mod_learnspells.cpp.o
/azerothcore/modules/mod-learn-spells-master/src/mod_learnspells.cpp:15:25: fatal error: no member named 'GetOption' in 'ConfigMgr'
        if (sConfigMgr->GetOption<bool>("LearnSpells.OnFirstLogin", 0))
            ~~~~~~~~~~  ^
1 error generated.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:7806: src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-learn-spells-master/src/mod_learnspells.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1235: src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/mod-learn-spells/actions/runs/800789436
