### ISSUE TITLE
Possible fixes in other forks :P

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-learn-spells#3]
Merge latest commit from https://github.com/Dreaxxx/mod-learn-spells

and missing commits from
https://github.com/talamortis/mod-learnspells

**Comment by BarbzYHOOL** [comment]
we need to make sure the missing spells are needed
and finally i'm not sure anymore about the feature to auto learn mount spell, seems out of place, shouldn't be in this module imo (one module = one function, and this one is about learning spells, not professions or other things)

**Comment by omghixd** [comment]
Agreed regarding BarbzYHOOL's statement in terms of what the module should learn and not. Mounts, professions and skills could be done by a separated module OR a configuration option "imo"
