### ISSUE TITLE
transfusion of life - sorcerers

### ISSUE THREAD

**Issue by Ligthsx** [azerothcore/mod-learn-spells#42]
The life transfusion spell that grants you at level 6 to witches, directly gives you rank 8.
which does not allow you to change mana for life and this was tested on the azerothcore emulator updated in may 2023
https://i.postimg.cc/G4kT5sPX/Screenshot-120.png[/img][/url]
https://i.postimg.cc/d7wZPt4w/Screenshot-121.png[/img][/url]

**Comment by duncrafter** [comment]
Can confirm, see : https://github.com/azerothcore/mod-learn-spells/issues/35

**Comment by jacpurg** [comment]
Can also confirm.  Our realm first level 6 warlock just brought it up.  Is there any intentions of resolving this issue?

**Comment by pangolp** [comment]
> Can also confirm. Our realm first level 6 warlock just brought it up. Is there any intentions of resolving this issue?

There are always intentions, but it depends on everyone's collaboration. From the people who generate the reports, and from the people who upload the pull requests, with the proposals. Sometimes modules are created by people, who after a while stop working on them, and the community takes over. But as part of the community, any of us can collaborate and solve the problem.

**Comment by Tony931023** [comment]
The module has an error because it provides all ranges from 1 - 8 of the life transfusion power at level 6, you just have to open the power book and check show all spell ranges and select the correct one

![imagen](https://github.com/azerothcore/mod-learn-spells/assets/4868094/8f6ae837-b4ef-462b-824a-8d813ea10203)
