### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by ide1234000** [azerothcore/mod-learn-spells#5]
When I tried to compile, i got an error

![Screenshot from 2019-04-01 23-45-04](https://user-images.githubusercontent.com/34786977/55381821-e6998280-54d8-11e9-8d5f-ce3c308abbe4.png)

BRANCH(ES):
master

AC HASH/COMMIT:
eae9aff

OPERATING SYSTEM:
Ubuntu 16.04 64

MODULES:
mod-learn-spells

**Comment by BarbzYHOOL** [comment]
Apparently there is a PR on the Core that addresses this, test it (related to ScriptPCH)

**Comment by Winfidonarleyan** [comment]
See https://github.com/azerothcore/azerothcore-wotlk/pull/1669

**Comment by gbmv33** [comment]
I use Linux too How i solve this?

**Comment by BarbzYHOOL** [comment]
test the PR gbmv33 please! Follow our wiki to know how

**Comment by gbmv33** [comment]
Just explain what's PR for me to take a test.

**Comment by BarbzYHOOL** [comment]
http://www.azerothcore.org/wiki/How-to-test-a-PR

**Comment by gbmv33** [comment]
testing...

**Comment by gbmv33** [comment]
tested  PR 1669 on ubuntu 18.04.2 LTS and works

**Comment by Winfidonarleyan** [comment]
So, need delete include ScriptPCH.h

**Comment by BarbzYHOOL** [comment]
Yes but also add the missing header probably.

**Comment by BarbzYHOOL** [comment]
@gbmv33 @ide1234000 test this please (BOTH of you) https://github.com/azerothcore/mod-learn-spells/pull/6

**Comment by ide1234000** [comment]
@BarbzYHOOL Very nice It’s work!

**Comment by BarbzYHOOL** [comment]
@ide1234000 can you post this on the PR to thank the author please? :)
