### ISSUE TITLE
Some spells are not learned

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-learn-spells#7]
mod-learn-spells is bugged because the command `.learn all my class` is bugged since there are missing spells. I think it's a core issue

So if you level up normally, you're missing some spells

example with a horde druid:
go from 1 to 80 with `.level 79`
then go to a druid trainer with `.tele elderrise` and see the missing spells

Related: https://github.com/azerothcore/azerothcore-wotlk/issues/2687

**Comment by Yehonal** [comment]
anytime I had to implement a "learn all" script, the best way to do it is reading the list of the spell from the trainer table and learn them all doing the right checks (level/rank) before

**Comment by BarbzYHOOL** [comment]
yes but what i said is just a theory of how the code works, because the issue is similar with the GM command, so I suppose it uses the same method as the GM command and it's missing spells which is kinda annoying :(

**Comment by BarbzYHOOL** [comment]
@Yehonal in fact, it taught me mangle while i didn't have the required talent, it's so wrong lol

the module should be done like you said

you haven't made a similar but working module??

**Comment by BarbzYHOOL** [comment]
checked the code quickly, it's probably just using a similar method as the command (it was probably copied from the command, hence why same bugs)
